# Numpy
Topics to be covered: 
Introduction to Numpy. Array Creation,Printing Arrays Basic Operations- Indexing, Slicing and Iterating Shape Manipulation - Changing shape,stacking and spliting of array Vector stacking

In [2]:
import numpy as np

In [10]:
#tmp = np.array(())
#print(tmp)
tmp1 = np.array([])
print(tmp1)
print(tmp1.dtype)
print(tmp1.shape)
print(tmp1.size)
print(tmp1.itemsize)
print(tmp1.ndim)

[]
float64
(0,)
0
8
1


In [11]:
tmp1 = np.array([1,2,3])
print(tmp1)
print(tmp1.dtype)
print(tmp1.shape)
print(tmp1.size)
print(tmp1.itemsize)
print(tmp1.ndim)

[1 2 3]
int32
(3,)
3
4
1


In [19]:
tmp1 = np.array([[1,2,3],[4,5,6],[1,2.,3]])
#tmp1 = np.array([[1,2,3],[4,5,6],[1,2,3]],dtype="float64")
print(tmp1)
print(tmp1.dtype)
print(tmp1.shape)
print(tmp1.size)
print(tmp1.itemsize)
print(tmp1.ndim)

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]]
float64
(3, 3)
9
8
2


In [26]:
tmp1 = np.array([[1,2,3],[4,5,6],[1,2.,3],[1,2.,3]])
print(tmp1)
print(tmp1.shape)
tmp2 =tmp1.reshape((3,4))
print(tmp2)
print(tmp2.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [1. 2. 3.]]
(4, 3)
[[1. 2. 3. 4.]
 [5. 6. 1. 2.]
 [3. 1. 2. 3.]]
(3, 4)


In [32]:
tmp1 = np.array([[1,2,3],[4,5,6],[1,2.,3],[1,2.,3]])
print(tmp1)
print(tmp1.T)
print(tmp1)
#tmp1.transpose()

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 4. 1. 1.]
 [2. 5. 2. 2.]
 [3. 6. 3. 3.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [42]:
tmp1 = np.array([[1,2,3],[4,5,6],[1,2.,3],[1,2.,3]])
print(tmp1)
print(tmp1[::,::])
print(tmp1[:,1])
print(tmp1[::,1])
print(tmp1[:,:2])
print(tmp1[1:,1:2])
print(tmp1[::,::-1])
print(tmp1[::-1,::-1])
print(tmp1[...])

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [1. 2. 3.]]
[2. 5. 2. 2.]
[2. 5. 2. 2.]
[[1. 2.]
 [4. 5.]
 [1. 2.]
 [1. 2.]]
[[5.]
 [2.]
 [2.]]
[[3. 2. 1.]
 [6. 5. 4.]
 [3. 2. 1.]
 [3. 2. 1.]]
[[3. 2. 1.]
 [3. 2. 1.]
 [6. 5. 4.]
 [3. 2. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [50]:
tmp = np.arange(10)
print(tmp)
print(tmp.reshape((5,2)))
print(tmp.reshape((10,1)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [55]:
tmp = np.random.random([3,3])
print(tmp)

[[0.98603349 0.06718779 0.16371802]
 [0.15556205 0.63714639 0.61557943]
 [0.65246882 0.96486057 0.47637107]]


In [60]:
tmp = np.linspace(1,100,15)
print(tmp)

[  1.           8.07142857  15.14285714  22.21428571  29.28571429
  36.35714286  43.42857143  50.5         57.57142857  64.64285714
  71.71428571  78.78571429  85.85714286  92.92857143 100.        ]


In [64]:
a = np.array([[1,1],[1,1]])
b = np.array([[2,2],[2,2]])
print(a+b)
print(a-b)
print(a/b)
print(a%b)
print(a*b)
print(a**b)
print(np.dot(a,b))

[[3 3]
 [3 3]]
[[-1 -1]
 [-1 -1]]
[[0.5 0.5]
 [0.5 0.5]]
[[1 1]
 [1 1]]
[[2 2]
 [2 2]]
[[1 1]
 [1 1]]
[[4 4]
 [4 4]]


In [84]:
a = np.arange(0,12).reshape(4,3)
print(a)
#print(a.min())
print(np.min(a))
print(np.max(a))
print(np.min(a,0))
print(np.min(a,1))
print(np.sum(a))
print(np.sum(a,0))
print(np.sum(a,1))
print(np.prod(a,1))
print(np.std(a,1))
print(np.mean(a,1))
print(np.median(a,1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
11
[0 1 2]
[0 3 6 9]
66
[18 22 26]
[ 3 12 21 30]
[  0  60 336 990]
[0.81649658 0.81649658 0.81649658 0.81649658]
[ 1.  4.  7. 10.]
[ 1.  4.  7. 10.]


In [88]:
a = np.arange(0,4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
print(a)
print(b)
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [96]:
a = np.arange(10,30).reshape(5,4)
print(a>12)
idx = np.where(a>12)
print(a[idx])
idx1 = np.where((a>12) & (a<26))
#print(idx1)
print(a[idx1])

[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[13 14 15 16 17 18 19 20 21 22 23 24 25]


In [101]:
a = np.arange(0,50).reshape(10,5)
print(a)
idx = np.where((a%2==0) & (a>24))
print(a[idx])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[26 28 30 32 34 36 38 40 42 44 46 48]


In [109]:
a = np.arange(0,50)
print(np.split(a,5))
print(np.split(a,[4,9]))
print(np.split(a,[2,4,6,8]))

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]), array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]
[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])]


In [113]:
d1 = np.genfromtxt("test1.csv",delimiter=",",dtype="U75")
print(d1)

[['A' 'B' 'C' 'D']
 ['1' '4' '7' '']
 ['2' '5' '8' '10']
 ['3' '6' '9' '']]
