# Numpy Basic Operations

In [1]:
import numpy as np

In [2]:
# Initialized array
a = np.array([])
print a

[]


In [3]:
# Un-initialized array,will have some random value
a= np.empty([2,3])
print a

[[  1.53477530e-316   1.53654455e-316   2.50026224e-315]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]]


In [4]:
a= np.array([1,2,3])
print a
print type(a)
print a.shape
print a.dtype
print a.size
print a.itemsize
print a.ndim

[1 2 3]
<type 'numpy.ndarray'>
(3L,)
int32
3
4
1


In [59]:
import sys
a = np.array([[1,2,3],[4,5,6]],dtype="int16")
print a
print a.shape
print sys.getsizeof(a)
print a.ndim

[[1 2 3]
 [4 5 6]]
(2L, 3L)
124
2


In [6]:
import sys
a = np.array([[1,2,3],[4,5,6]],dtype="float32")
print a
print a.shape
print sys.getsizeof(a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
(2L, 3L)
136


In [67]:
# Shorthand for defaults
tmp = np.int_([1,2,3])
print tmp
print tmp.dtype
tmp = np.bool_([1,2,3])
print tmp
print tmp.dtype
tmp = np.float_([1,2,3])
print tmp
print tmp.dtype
tmp = np.complex_([1,2,3])
print tmp
print tmp.dtype

[1 2 3]
int32
[ True  True  True]
bool
[ 1.  2.  3.]
float64
[ 1.+0.j  2.+0.j  3.+0.j]
complex128


In [57]:
# Linearly seperated value within range
lin = np.linspace(1,20) # default 50 numbers will be printed within 1-20
print lin
lin = np.linspace(1,20,10) # 10 values will be printed within 1-20
print lin

[  1.           1.3877551    1.7755102    2.16326531   2.55102041
   2.93877551   3.32653061   3.71428571   4.10204082   4.48979592
   4.87755102   5.26530612   5.65306122   6.04081633   6.42857143
   6.81632653   7.20408163   7.59183673   7.97959184   8.36734694
   8.75510204   9.14285714   9.53061224   9.91836735  10.30612245
  10.69387755  11.08163265  11.46938776  11.85714286  12.24489796
  12.63265306  13.02040816  13.40816327  13.79591837  14.18367347
  14.57142857  14.95918367  15.34693878  15.73469388  16.12244898
  16.51020408  16.89795918  17.28571429  17.67346939  18.06122449
  18.44897959  18.83673469  19.2244898   19.6122449   20.        ]
[  1.           3.11111111   5.22222222   7.33333333   9.44444444
  11.55555556  13.66666667  15.77777778  17.88888889  20.        ]


# Numpy Indexing, Slicing Operations

In [7]:
a = np.array([[1,2,3],[4,5,6]])
print a[0]
print a[:,:]

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [32]:
a = np.arange(20)
print a.shape
a = a.reshape(5,4)
print a.shape
print a,"#"*5,
print a[:,:2]

(20L,)
(5L, 4L)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] ##### [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]]


In [33]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
a.T # Transpose

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [31]:
a.transpose() # Transpose

array([[1, 3],
       [2, 4]])

In [81]:
print a*2 # multiple 2 with each element
print a*a # multiple 2 with each element
print a
print np.dot(a,a.T) # a.T because in a(m,n), m != n of a hence, a.T (m,n) will match the number of column and rows
a.T

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]


array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int16)

# Iterating over array element

In [36]:
print a,"\n"
b = iter(a)
print b.next()
print b.next()

# or
for itm in np.nditer(a):
    print itm,

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[0 1 2 3]
[4 5 6 7]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19


# Changing shape

In [37]:
a.shape
b = a.reshape(10,2)
print a.shape,"\n",a
print b.shape,"\n",b

(5L, 4L) 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(10L, 2L) 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


# Stacking array vstack and hstack

In [38]:
a = np.array(([1,2],[3,4]))
b = np.array(([5,6],[7,8]))
v = np.vstack([a,b])
h = np.hstack([a,b])
print v.shape,"\n",v
print h.shape,"\n",h

(4L, 2L) 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(2L, 4L) 
[[1 2 5 6]
 [3 4 7 8]]


# Standard functions for nparray

In [39]:
a

array([[1, 2],
       [3, 4]])

In [40]:
print a.min()
print a.max()
print a.std()
print a.mean()
print np.sin(a)
print np.cos(a)
print np.tan(a)

1
4
1.11803398875
2.5
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
[[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]


# Filtering specific values from array

In [45]:
a = np.arange(20)
a = a.reshape(5,4)
print a
print a[a>5] # Will return all the values for which condition is "True"
print a[a>8]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 9 10 11 12 13 14 15 16 17 18 19]


In [46]:
print a
b = np.where(a>5) # Will return the index of those values for which condition is "True"
print a[b] # Will return the values at the supplied index

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Generating diagonal,zeros and ones matrix

In [88]:
print np.zeros((2,3))
print np.ones((2,3))
print np.eye(3)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Open a csv file and read them

In [20]:
data = np.genfromtxt(r"C:\Users\psoni\Desktop\Py_Test_Program\numpy_pandas\pd\education_sta.csv",delimiter=",")
print data[0] # will return all string as nan


[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan]


In [53]:
data = np.genfromtxt(r"C:\Users\psoni\Desktop\Py_Test_Program\numpy_pandas\pd\education_sta.csv",delimiter=",",dtype="|U75")
print data[0] # dtype == U75 will return all string name as well
print data[:,0]
print data[0:3,0]
print data[1:3,0] # Skipping the header part


[u'Year' u'Agriculture' u'Architecture' u'Art and Performance' u'Biology'
 u'Business' u'Communications and Journalism' u'Computer Science'
 u'Education' u'Engineering' u'English' u'Foreign Languages'
 u'Health Professions' u'Math and Statistics' u'Physical Sciences'
 u'Psychology' u'Public Administration' u'Social Sciences and History'
 u'survivied' u'survivied2' u'survivied3']
[u'Year' u'1970' u'1971' u'1972' u'1973' u'1974' u'1975' u'1976' u'1977'
 u'1978' u'1979' u'1980' u'1981' u'1982' u'1983' u'1984' u'1985' u'1986'
 u'1987' u'1988' u'1989' u'1990' u'1991' u'1992' u'1993' u'1994' u'1995'
 u'1996' u'1997' u'1998' u'1999' u'2000' u'2001' u'2002' u'2003' u'2004'
 u'2005' u'2006' u'2007' u'2008' u'2009' u'2010' u'2011']
[u'Year' u'1970' u'1971']
[u'1970' u'1971']
